name: Deploy Vite to GitHub Pages

on:
  push:
    branches: [ main ]   # change if your default branch isn't main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  APP_DIR: botbygging   # <--- your Vite app subfolder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Install deps
        working-directory: ${{ env.APP_DIR }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        working-directory: ${{ env.APP_DIR }}
        run: npm run build

      # SPA fallback: make 404.html same as index.html
      - name: Create 404.html for SPA
        working-directory: ${{ env.APP_DIR }}
        run: cp dist/index.html dist/404.html

      
      - name: Remove CNAME if exists
        working-directory: ${{ env.APP_DIR }}
        run: rm -f dist/CNAME


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.APP_DIR }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
